### ISSUE TITLE
Lists delimiter character

### ISSUE THREAD

**Issue by iax7** [mustache/mustache.github.com#104]
When working with lists, sometimes you need to have a delimiter character like a comma, to separate them, but when the last item is rendered that comma should not be added.

I'm thinking in something like this as a starting point:
```
export no_proxy="{{#noproxy}}{{.}}{{=,}}{{/noproxy}}"
```
the `{{=,}}` is the delimiting character that should be used when is not the last item.

**Comment by jobol** [comment]
That an is interesting proposal to my eyes. I'll add it in my implementation but not with the char =.
I think that the char , is a better choice. It will be {{,,}} or {{,;}} or {{, }}.

**Comment by bobthecow** [comment]
There's currently nowhere in the mustache spec where something typed inside curly brackets is printed. Using a comma that's inside a tag like this is akin to using a function or variable name to decide what to print, rather than passing data like a string :)

To be consistent, it should probably have the value between matched tags, the way sections, blocks, etc work.

**Comment by jobol** [comment]
Agreed.

I had a ideas about putting the data to print between {{,}} and the closing enumeration {{/...}} but it seems more complicated to implement because it currently doesn't enforce restriction on the enclosed content.

I also mind about specifying the separator in {{/....}} like in {{,,/...}} or {{/...,,}} but it raise escaping issues.

**Comment by ppKrauss** [comment]
No solution here?

It is a classic problem, **that makes people to abandon Mustache**.

**Comment by Auxallrymail123** [comment]
> When working with lists, sometimes you need to have a delimiter character like a comma, to separate them, but when the last item is rendered that comma should not be added.
> 
> I'm thinking in something like this as a starting point:
> 
> ```
> export no_proxy="{{#noproxy}}{{.}}{{=,}}{{/noproxy}}"
> ```
> 
> the `{{=,}}` is the delimiting character that should be used when is not the last item.

https://github.com/mustache/mustache.github.com/issues/104#issue-279915826

**Comment by jgonggrijp** [comment]
Closing this because this repository is about the website and not about the Mustache template language. Please take comments about the template language to https://github.com/mustache/spec/discussions.

Previous discussions about this particular topic can be found via https://github.com/mustache/spec/discussions/163, https://github.com/mustache/spec/discussions/153 and https://github.com/mustache/spec/discussions/164.
