### ISSUE TITLE
Elm implementation

### ISSUE THREAD

**Issue by emmabastas** [mustache/mustache.github.com#163]
Hello, I implemented the mustache specification in Elm over at https://github.com/emmabastas/elm-mustache/

It supports (as in, passes the tests in mustache/spec) every non-optional feature except for partials (would it make sense to have this in a niche browser language without file access?) and it doesn't preserve `\r\n` -style line endings (for no particular reason, should fix that at some point).

I know that [this](https://github.com/truqu/elm-mustache/) Elm implementation is already linked from the website. However, that package is more limited (supports only normal variables and boolean sections, and does not handle standalone tags and other edge cases) and has since been archived.

**Comment by jgonggrijp** [comment]
I'm in favor in principle; your implementation does look more complete and up to date than the currently listed one. However, I am currently travelling and I also have not solved https://github.com/mustache/mustache.github.com/pull/159#issuecomment-1991531423 yet, which I feel this is another instance of. My own JavaScript implementation (Wontache), which I think is superior to the alternatives, is not yet listed on the homepage for the same reason. For this reason, I cannot promise to follow up on your suggestion any time soon.

You can help me in two ways:

1. Prepare a pull request in which you substitute your implementation for truqu's. In this case I will probably merge it, because the other implementation is end of life.
2. Leave a suggestion in #159 on how to generally deal with having multiple implementations for the same programming language. I can use some input on that.

**Comment by emmabastas** [comment]
Thank you for the reply and for ingesting some very actionable things I can do to help :-)

**Comment by emmabastas** [comment]
> Prepare a pull request in which you substitute your implementation for truqu's. In this case I will probably merge it, because the other implementation is end of life.

Made a pull request to update the link  #164

**Comment by emmabastas** [comment]
> Leave a suggestion in https://github.com/mustache/mustache.github.com/pull/159 on how to generally deal with having multiple implementations for the same programming language. I can use some input on that.

I gave some input https://github.com/mustache/mustache.github.com/pull/159#issuecomment-2275173024
