### ISSUE TITLE
What characters are allowed in a tag name/key?

### ISSUE THREAD

**Issue by davesmiths** [mustache/mustache.github.com#75]
Hi 

What characters are allowed as a tag name/key?

I looked in the documentation but couldn't find anything. For example is {{first-name}} and {{firstName}} ok, or is it only lowercase a-z?

all the best
Dave

**Comment by locks** [comment]
I believe the rules for tag name resolution are layout out in the spec at https://github.com/mustache/spec/blob/master/specs/sections.yml . 
`{{first-name}}` should be fine, I think you run into trouble if your property name has a `.` in it.

**Comment by davesmiths** [comment]
Thanks locks, that was the doc I needed

**Comment by bobthecow** [comment]
Names can't start or end with whitespace or any of the tag sigils (e.g. `#` or `^`). They can't contain a `.` or the current tag closing characters (by default that's `}}`). Other than that, the spec doesn't place any restrictions on tag names. 

Not all implementations are that flexible, but I'd argue that's because they're not spec compliant ;)
